/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.util.ArrayList;
import java.util.Arrays;
import processing.Search;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        int res = Search.continuityAboveValue(
            Arrays.asList(new Double(0), new Double(3), new Double(4), new Double(5), new Double(0)),
            1, // indexBegin
            3, // indexEnd
            2, // threshold
            3  // winLength
        );
        System.out.println("res = " + res);
    }
}
